SET session_replication_role = 'replica';

TRUNCATE TABLE "metodos_pago" CASCADE;

INSERT INTO "metodos_pago" ("id", "nombre", "descripcion", "activo", "created_at") VALUES
(1, 'Efectivo', 'Fabulas, male, credo, mererer de meis civibus, si ad. Propter se ipsos diligant. Quod et posse fieri intellegimus. Sunt aliae quoque causae, sed multitudinem haec maxime allicit, quod ita.', '1', '2024-09-26 15:53:43'),
(2, 'Pago por Venmo', 'Inanes divitiarum, gloriae, dominationis, libidinosarum etiam voluptatum. Accedunt. Sed sine hoc institutionem omnino amicitiae.', '1', '2024-09-26 16:00:05'),
(3, 'Pago por Bizum', 'Enim medicorum scientiam non ipsius artis, sed bonae valetudinis causa probamus, et gubernatoris. Et amicitia cum voluptate conectitur. Quo etiam Democritus haeret, turbulenta.', '1', '2024-09-26 16:08:43'),
(4, 'Débito automático', 'Medium videretur, cum omni dolore detracto, nam quoniam, cum privamur dolore, ipsa. Afferat et eos quasi concordia quadam placet ac leniat. Temperantia est enim, quod tibi.', '1', '2024-09-26 16:12:36'),
(5, 'Criptomonedas', 'Sed sine hoc institutionem omnino amicitiae non posse iucunde vivi, nisi sapienter, honeste iusteque vivatur. Sola voluptas esset, quae quasi titillaret sensus, ut ita dicam, et ad. Testibus, si infantes pueri, mutae etiam bestiae paene loquuntur magistra ac duce.', '0', '2024-09-26 16:20:10'),
(6, 'Tarjeta de crédito', 'Et comparandae voluptatis -- Quam autem ego. Pro patria et pro suis suscipit, ut non modo quid nobis probaretur, sed etiam. Debilitatem animi multi parentes, multi. Quos ego posse iudicare arbitrarer, plura suscepi veritus ne movere hominum studia viderer, retinere. Quae quia certa esse non.', '0', '2024-09-26 16:24:44'),
(7, 'Pago por OXXO', 'Munere vitae optimum et verissimum sit, exquirere? An. Spe proposita fore levius aliquando, nulla praeterea. Finitas habet cupiditates, neglegit mortem, de diis.', '1', '2024-09-26 16:30:17'),
(8, 'Pago por QR', 'Quod tibi parum videtur eruditus, ea causa. Numeris, astris contereret, quae et a falsis initiis profecta.', '1', '2024-09-26 16:36:45'),
(9, 'Pago contra entrega', 'Causa, mox videro; interea hoc tenebo, si ob aliquam causam ista.', '1', '2024-09-26 16:37:53'),
(10, 'Amazon Pay', 'Posset nec ulla pars vacuitate doloris sine iucundo motu voluptatis. Sit id, de quo Lucilius: ''ferreum scriptorem'', verum.', '1', '2024-09-26 16:47:38'),
(11, 'Pago por Samsung Pay', 'Ab hoc, qui eum unum secutus esset, nollem. Ita effici complexiones et copulationes et adhaesiones. Liberemus. Ut enim aeque doleamus.', '0', '2024-09-26 16:53:56'),
(12, 'Pago con tarjeta de regalo', 'Epicuro scriptum est et ad tranquillitatem ferant, quid est cur verear. Ex futuris, sed expectat illa, fruitur praesentibus ab iisque M. Brutus. Quod ita putant dici ab illo.', '1', '2024-09-26 16:55:42'),
(13, 'Western Union', 'Accusantium doloremque laudantium, totam rem aperiam. Tam crudelis fuisse, nihil ut de utilitatibus, nihil ut de utilitatibus, nihil ut de omni. Partus ancillae sitne in fructu habendus, disseretur inter principes civitatis, P. Scaevolam. Aeque doleamus animo, cum corpore dolemus, fieri tamen permagna accessio potest, si.', '0', '2024-09-26 17:02:33'),
(14, 'Pago móvil', 'Aliae suo nutu recte ferentur, primum erit hoc quasi, provincias atomis dare, quae. Esset. Quam ob rem voluptas expetenda, fugiendus dolor sit. Sentiri haec putat, ut calere. Desistemus. Nisi autem rerum natura duo. Commune vitium, illae Epicuri propriae ruinae: censet enim eadem illa atomorum, in quo nihil. Multoque hoc melius nos veriusque quam Stoici. Illi.', '0', '2024-09-26 17:11:46'),
(15, 'Pago por SPEI', 'Quaestionem de finibus bonorum et malorum, id est laborum et dolorum. Epicuri non probo, inquam. De cetero vellem. Servare id, quod sentiant non esse faciendum, ii voluptatem maximam adipiscuntur. Perdiscere ludus esset. Quam ob rem tandem, inquit.', '0', '2024-09-26 17:15:39'),
(16, 'PayPal', 'Me ab eo nos abducat? Sin laboramus, quis. Voluptatem. Homines optimi non intellegunt totam rationem.', '1', '2024-09-26 17:22:38'),
(17, 'Cheque', 'E physicis et fortitudo sumitur contra mortis timorem et constantia contra. Et dolorem ipsum per se ipsas tam expetendas, quam nostras expeteremus, quo loco videtur quibusdam.', '1', '2024-09-26 17:23:58'),
(18, 'Pago con vales', 'Quo pertineant non intellegamus, tu tam egregios viros censes tantas. Et ratione administrari neque maiorem. Voce naturae sic eam firme graviterque comprehenderit. Numquam adquiescere. Quodsi ne ipsarum quidem virtutum laus, in qua maxime ceterorum philosophorum. Bene vivendi recteque faciendi consilia referenda, quid sequatur.', '0', '2024-09-26 17:29:50'),
(19, 'Apple Pay', 'Fruentem et animo et corpore voluptatibus nullo dolore nec impediente nec inpendente, quem. Facile, ut mihi videtur, expediunt. Ut enim virtutes, de quibus et. Varias reprehensiones incurreret. Nam quibusdam.', '0', '2024-09-26 17:38:23'),
(20, 'Pago por Alipay', 'Improborum facta primo suspicio insequitur, dein sermo atque fama, tum accusator, tum iudex; Multi. Metu contineret, saluti prospexit civium, qua intellegebat contineri suam. Facillime perspici potest: Constituamus aliquem magnis, multis, perpetuis fruentem et animo et corpore. Nostris non legantur? Quamquam, si plane sic verterem Platonem aut Aristotelem, ut verterunt nostri.', '0', '2024-09-26 17:45:24'),
(21, 'Pago por domiciliación', 'Quod coniunctione tali sit aptius. Quibus ex omnibus iudicari potest non modo quid nobis. Inquam, ''Tite!'' lictores, turma omnis chorusque: ''chaere, Tite!'' hinc hostis mi. Et voluptatibus maximis saepe priventur et. Inpendente, quem tandem hoc statu praestabiliorem aut magis expetendum possimus dicere? Inesse enim.', '0', '2024-09-26 17:47:33'),
(22, 'Google Pay', 'Erga amicum, quo in se ipsum, quosque labores propter suam voluptatem susciperet.', '1', '2024-09-26 17:48:36'),
(23, 'Transferencia bancaria', 'Cum tractat locos ab Aristotele ante tractatos? Quid? Epicurei num desistunt de. Gerendarum. Sic e physicis et fortitudo sumitur contra mortis timorem et. Animi noctesque diesque exeduntur, a diis inmortalibus supplicii causa importari putant. Quae autem inanes.', '0', '2024-09-26 17:56:40'),
(24, 'Stripe', 'Quidque efficiat, de materia disseruerunt, vim et causam efficiendi. Aliquid falsi pro vero probatum sit, sublatum esse omne iudicium veri et falsi putat. Confirmat. Possit et sine metu degendae praesidia firmissima. -- Filium morte multavit. -- Si sine. Eo est consecutus? -- Laudem et. Philosophia audeam scribere? Quamquam a te ipso id.', '0', '2024-09-26 18:05:54'),
(25, 'Pago por Zelle', '--, quamquam autem et praeterita grate meminit et praesentibus ita potitur, ut animadvertat. Scribere. Facete is quidem, sicut alia; sed neque tam docti tum erant. Ex cupiditatibus odia, discidia, discordiae, seditiones, bella nascuntur, nec eae se foris solum. Rutilius multo etiam magis, quorum ille iudicium reformidans Tarentinis ait se et Consentinis et Siculis. Quicquid porro animo cernimus, id omne oritur a sensibus; qui si omnes veri erunt.', '0', '2024-09-26 18:09:22'),
(26, 'Pago por Mercado Pago', 'Habeatur disciplina, quam gravis, quam continens, quam severa sit. Non enim hanc.', '1', '2024-09-26 18:15:09'),
(27, 'Pago por WeChat Pay', 'Posse, quam ex hoc percipiatur, quod videamus esse finitum. In dialectica autem. Multos, sed imperitos --, quamquam autem.', '1', '2024-09-26 18:16:49'),
(28, 'MoneyGram', 'Igitur Epicuri non probo, inquam. De cetero vellem equidem aut ipse doctrinis fuisset instructior. Torquate, quid huic Triario litterae, quid historiae cognitioque rerum, quid.', '1', '2024-09-26 18:18:41'),
(29, 'Pago con puntos', 'Debent, quod et acutum genus est et expedita distinctio.', '1', '2024-09-26 18:28:29'),
(30, 'Tarjeta de débito', 'Quo melius viveremus, eas ergo artes persequeretur, vivendi artem tantam tamque et operosam. Quod omnium philosophorum sententia tale debet esse, ut ad id omnia referri. Et ignavia semper animum excruciant et semper sollicitant turbulentaeque sunt, sic inprobitas.', '0', '2024-09-26 18:30:55');

