server:
  port: ${SERVER_PORT:8989}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: catalogs

  
  datasource:
    # url: jdbc:postgresql://localhost:5432/tienda_db
    url: jdbc:postgresql://postgres:5432/tienda_db
    username: tienda_user
    password: tienda_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    # disable open-in-view to avoid lazy-loading during view rendering
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  

# jwt:
#   private-key: classpath:certificates/private.key
#   public-key: classpath:certificates/public.key
  # expiration: 43200000 # 12 horas en milisegundos

logging:
  level:
    com.tienda.auth: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"